import Phaser from 'phaser';
import { ObstacleSpawner } from '../systems/ObstacleSpawner.js';
import { PokemonSpawner } from '../systems/PokemonSpawner.js';
import { StickerBook } from '../systems/StickerBook.js';
import { createStorage } from '../utils/storage.js';
import { POKEMON } from '../data/pokemon.js';
import { BIOMES } from '../data/biomes.js';
import { BiomeManager } from '../systems/BiomeManager.js';

export default class GameScene extends Phaser.Scene {
  constructor() {
    super({ key: 'GameScene' });
  }

  preload() {
    // Vi laddar 43 assets — höj från Phasers default 32 så alla startar parallellt.
    this.load.maxParallelDownloads = 64;
    this.load.on('loaderror', (file) => {
      // Tyst fail för audio så v1 fungerar utan ljudfiler.
      // Pokémon-sprite-fel ska däremot synas.
      if (file.type === 'audio') return;
      console.warn('Asset load error:', file.key, file.src);
    });
    for (const p of POKEMON) {
      this.load.image(`pokemon-${p.id}`, `pokemon/${p.id}.png`);
    }
    // Karaktär + biom-specifika bakgrunder och mark.
    this.load.image('bike', 'characters/bike.png');
    this.load.image('bg-forest', 'backgrounds/forest.png');
    this.load.image('bg-beach', 'backgrounds/beach.png');
    this.load.image('bg-cave', 'backgrounds/cave.png');
    this.load.image('ground-forest', 'grounds/forest.png');
    this.load.image('ground-beach', 'grounds/beach.png');
    this.load.image('ground-cave', 'grounds/cave.png');
    // Hinder
    this.load.image('obstacle-rock', 'obstacles/rock.png');
    this.load.image('obstacle-log', 'obstacles/log.png');
    this.load.image('obstacle-puddle', 'obstacles/puddle.png');
    this.load.image('obstacle-shell', 'obstacles/shell.png');
    this.load.image('obstacle-stalagmite', 'obstacles/stalagmite.png');
    // Ljud — load misslyckas tyst om filer saknas.
    this.load.audio('bgm-forest', 'audio/bgm-forest.wav');
    this.load.audio('bgm-beach', 'audio/bgm-beach.wav');
    this.load.audio('bgm-cave', 'audio/bgm-cave.wav');
    this.load.audio('sfx-jump', 'audio/sfx-jump.wav');
    this.load.audio('sfx-pickup', 'audio/sfx-pickup.wav');
    this.load.audio('sfx-bonk', 'audio/sfx-bonk.wav');
    this.load.audio('sfx-shiny', 'audio/sfx-shiny.wav');
  }

  create() {
    const w = this.scale.width;
    const h = this.scale.height;

    const groundHeight = 120;
    const groundY = h - groundHeight / 2;

    // Bakgrund (texture sätts av handleBiomeSwitch / startBiome nedan)
    this.bgImage = this.add.image(w / 2, h / 2, 'bg-forest')
      .setDisplaySize(w, h)
      .setDepth(0);

    // Mark — TileSprite med biom-textur (sätts till startbiomets nedan)
    this.ground = this.add.tileSprite(w / 2, groundY, w, groundHeight, 'ground-forest')
      .setDepth(1);

    // Osynlig physics-mark för kollision.
    this.groundBody = this.physics.add.staticImage(w / 2, groundY).setSize(w, groundHeight).setVisible(false);
    this.groundBody.refreshBody();

    // Cykel — riktig sprite (96x96 generated by FLUX.2)
    const bikeX = w * 0.25;
    const bikeY = groundY - groundHeight / 2 - 48;
    this.bike = this.physics.add.sprite(bikeX, bikeY, 'bike').setDepth(5);
    this.bike.setCollideWorldBounds(true);
    this.bike.body.setSize(60, 60);
    this.physics.add.collider(this.bike, this.groundBody);

    // Bake svart outline in i obstacle-texturer (en gång) → ingen runtime-glow.
    ['obstacle-rock', 'obstacle-log', 'obstacle-puddle', 'obstacle-shell', 'obstacle-stalagmite']
      .forEach((k) => this.bakeOutline(k, 1, '#000000'));

    this.baseSpeed = 200;
    this.maxSpeed = 360;
    this.scrollSpeed = this.baseSpeed;
    this.startTime = this.time.now;

    // Hindergenerator
    this.obstacleSpawner = new ObstacleSpawner({
      obstacleTypes: ['rock'],
      minIntervalMs: 1500,
      spawnWindowMs: 1500,
    });
    this.obstacles = this.physics.add.group({ allowGravity: false, immovable: true });

    const glitterKey = 'glitter';
    if (!this.textures.exists(glitterKey)) {
      const g = this.add.graphics();
      g.fillStyle(0xffffff, 1);
      g.fillCircle(4, 4, 4);
      g.generateTexture(glitterKey, 8, 8);
      g.destroy();
    }

    // Biom-manager
    this.biomeManager = new BiomeManager({
      biomes: BIOMES,
      rotationMs: 30000,
      onSwitch: (b) => this.handleBiomeSwitch(b),
    });

    const startBiome = this.biomeManager.current();
    this.bgImage.setTexture(`bg-${startBiome.id}`).setDisplaySize(w, h);
    this.ground.setTexture(`ground-${startBiome.id}`);
    this.cameras.main.setBackgroundColor(startBiome.bgColor);

    // Spawners initieras med startbiomets data.
    this.obstacleSpawner.setObstacleTypes(startBiome.obstacleTypes);

    this.physics.add.overlap(this.bike, this.obstacles, (bike, obstacle) => {
      this.handleBonk(obstacle);
    });
    this.bonkUntilTime = 0;

    // Klistermärkesbok
    this.stickerBook = new StickerBook({
      storage: createStorage(),
      key: 'pokemoncykelspel.stickers',
    });

    // Pokémon-spawner med startbiomets ids
    this.pokemonSpawner = new PokemonSpawner({
      pokemonIds: startBiome.pokemonIds,
      minIntervalMs: 3000,
      spawnWindowMs: 2000,
      shinyChance: 1 / 50,
    });
    this.pokemons = this.physics.add.group({ allowGravity: false });

    // Tracking för pokemon-spawner gap-regel
    this.timeSinceLastObstacleSpawn = 9999;

    this.physics.add.overlap(this.bike, this.pokemons, (bike, mon) => this.handlePokemonPickup(mon));

    const homeBtn = this.add.text(20, 20, '← Hem', {
      fontFamily: 'Arial',
      fontSize: '24px',
      color: '#ffffff',
      backgroundColor: '#000000aa',
      padding: { x: 10, y: 5 },
    }).setInteractive({ useHandCursor: true }).setScrollFactor(0).setDepth(1000);
    homeBtn.on('pointerdown', () => this.scene.start('HomeScene'));

    this.events.once('shutdown', () => {
      if (this.bgm) { this.bgm.stop(); this.bgm.destroy(); }
    });

    // Tap → hopp om vi står på marken.
    this.input.on('pointerdown', () => this.tryJump());

    // Score-system
    this.score = 0;
    this.initialHighScore = createStorage().get('pokemoncykelspel.highscore') || 0;
    this.highScore = this.initialHighScore;
    this.beatRecord = false;

    this.scoreText = this.add.text(w / 2, 24, '0', {
      fontFamily: 'Arial Black', fontSize: '44px',
      color: '#ffffff', stroke: '#1d4ed8', strokeThickness: 6,
    }).setOrigin(0.5, 0).setDepth(1500).setScrollFactor(0);

    this.highScoreText = this.add.text(w - 24, 28, `🏆 ${this.highScore}`, {
      fontFamily: 'Arial Black', fontSize: '24px',
      color: '#fde047', stroke: '#000000', strokeThickness: 4,
    }).setOrigin(1, 0).setDepth(1500).setScrollFactor(0);

    this.safeBgm(`bgm-${startBiome.id}`);
  }

  tryJump() {
    if (this.bike.body.blocked.down || this.bike.body.touching.down) {
      this.bike.setVelocityY(-700);
      this.safePlay('sfx-jump', { volume: 0.6 });
    }
  }

  spawnObstacle(type) {
    const w = this.scale.width;
    const groundTop = this.scale.height - 120;
    const key = `obstacle-${type}`;
    const obstacle = this.obstacles.create(w + 50, groundTop, key).setDepth(4).setOrigin(0.5, 1);
    obstacle.setVelocityX(-this.scrollSpeed);
    obstacle.body.setSize(40, 40);
    obstacle.body.setOffset((obstacle.width - 40) / 2, obstacle.height - 40);
    obstacle.setData('type', type);
    obstacle.setData('ring', this.attachRing(obstacle, w + 50, groundTop - 30, 0xef4444));
  }

  handleBonk(obstacle) {
    if (this.time.now < this.bonkUntilTime) return; // redan i bonk-läge
    this.bonkUntilTime = this.time.now + 500;

    // Förstör hindret + dess ring så vi inte triggas igen.
    const ring = obstacle.getData('ring');
    if (ring) ring.destroy();
    obstacle.destroy();

    // Kort sprite-tint + camera shake.
    this.bike.setTint(0xff8888);
    this.safePlay('sfx-bonk', { volume: 0.7 });
    this.cameras.main.shake(150, 0.005);
    this.time.delayedCall(300, () => this.bike.clearTint());

    this.showFloatingText('Hoppsan!', this.bike.x + 60, this.bike.y - 80, '#fecaca', '#b91c1c');
  }

  spawnPokemon({ pokemonId, shiny }) {
    const w = this.scale.width;
    const groundTop = this.scale.height - 120;
    const key = `pokemon-${pokemonId}`;
    const mon = this.pokemons.create(w + 50, groundTop - 30, key).setDepth(4).setScale(1.35);
    mon.setVelocityX(-this.scrollSpeed);
    mon.body.setSize(45, 45);
    mon.setData('pokemonId', pokemonId);
    mon.setData('shiny', shiny);
    if (shiny) {
      mon.setTint(0xffffaa);
      mon.postFX.addShine(0.5, 1, 6, false);
      const trail = this.add.particles(0, 0, 'glitter', {
        follow: mon,
        lifespan: 700,
        speed: { min: 30, max: 80 },
        scale: { start: 0.7, end: 0 },
        tint: [0xffd700, 0xffffaa, 0xffffff, 0xff99ff],
        quantity: 1,
        frequency: 70,
        blendMode: 'ADD',
      });
      trail.setDepth(4);
      mon.setData('trail', trail);
    }
    mon.setData('ring', this.attachRing(mon, w + 50, groundTop - 30, 0x22c55e, 70));
  }

  attachRing(target, x, y, color, radius = 50) {
    const ring = this.add.circle(x, y, radius, 0, 0)
      .setStrokeStyle(4, color, 0.6)
      .setDepth(3);
    this.physics.add.existing(ring);
    ring.body.setAllowGravity(false);
    ring.body.setVelocityX(-this.scrollSpeed);
    return ring;
  }

  bakeOutline(textureKey, thickness, color) {
    if (!this.textures.exists(textureKey)) return;
    const tex = this.textures.get(textureKey);
    const src = tex.getSourceImage();
    const w = src.width + thickness * 2;
    const h = src.height + thickness * 2;

    const canvas = document.createElement('canvas');
    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext('2d');

    for (let dx = -thickness; dx <= thickness; dx++) {
      for (let dy = -thickness; dy <= thickness; dy++) {
        if (dx === 0 && dy === 0) continue;
        ctx.drawImage(src, thickness + dx, thickness + dy);
      }
    }
    ctx.globalCompositeOperation = 'source-in';
    ctx.fillStyle = color;
    ctx.fillRect(0, 0, w, h);
    ctx.globalCompositeOperation = 'source-over';
    ctx.drawImage(src, thickness, thickness);

    this.textures.remove(textureKey);
    this.textures.addCanvas(textureKey, canvas);
  }

  handlePokemonPickup(mon) {
    if (mon.getData('picked')) return;
    mon.setData('picked', true);
    const pokemonId = mon.getData('pokemonId');
    const shiny = mon.getData('shiny');

    this.stickerBook.markSeen({ id: pokemonId, shiny });
    this.safePlay(shiny ? 'sfx-shiny' : 'sfx-pickup', { volume: 0.7 });

    if (shiny) this.spawnGlitter(mon.x, mon.y);

    // Score upp
    this.score += shiny ? 3 : 1;
    this.scoreText.setText(this.score);
    if (this.score > this.highScore) {
      this.highScore = this.score;
      this.highScoreText.setText(`🏆 ${this.highScore}`);
      createStorage().set('pokemoncykelspel.highscore', this.highScore);
      if (!this.beatRecord && this.initialHighScore > 0) {
        this.beatRecord = true;
        this.showFloatingText('NYTT REKORD!', this.scale.width / 2, 120, '#fde047', '#1d4ed8');
      }
    }

    this.showFloatingText(shiny ? 'GLITTRIG!' : 'Bra jobbat!', this.bike.x + 60, this.bike.y - 80, '#bbf7d0', '#166534');

    const ring = mon.getData('ring');
    if (ring) {
      this.tweens.add({
        targets: ring,
        alpha: 0,
        scale: 1.6,
        duration: 500,
        onComplete: () => ring.destroy(),
      });
    }

    const trail = mon.getData('trail');
    if (trail) {
      trail.stop();
      this.time.delayedCall(800, () => trail.destroy());
    }

    this.tweens.add({
      targets: mon,
      y: mon.y - 80,
      alpha: 0,
      duration: 600,
      onComplete: () => mon.destroy(),
    });
  }

  showFloatingText(text, x, y, fillColor, strokeColor) {
    const t = this.add.text(x, y, text, {
      fontFamily: 'Arial Black',
      fontSize: '60px',
      color: fillColor,
      stroke: strokeColor,
      strokeThickness: 8,
      align: 'center',
    }).setOrigin(0.5).setDepth(2500).setScale(0.3);

    this.tweens.add({
      targets: t,
      scale: 1.1,
      duration: 220,
      ease: 'Back.out',
      onComplete: () => {
        this.tweens.add({
          targets: t,
          alpha: 0,
          y: t.y - 50,
          duration: 600,
          delay: 350,
          onComplete: () => t.destroy(),
        });
      },
    });
  }

  spawnGlitter(x, y) {
    const particles = this.add.particles(x, y, 'glitter', {
      lifespan: 800,
      speed: { min: 100, max: 250 },
      scale: { start: 1, end: 0 },
      tint: [0xffd700, 0xffffaa, 0xffffff],
      quantity: 30,
      emitting: false,
    });
    particles.explode(30, x, y);
    this.time.delayedCall(1000, () => particles.destroy());
  }

  safePlay(key, config = {}) {
    if (this.cache.audio.exists(key)) {
      this.sound.play(key, config);
    }
  }

  safeBgm(key) {
    if (this.bgm) { this.bgm.stop(); this.bgm.destroy(); this.bgm = null; }
    if (this.cache.audio.exists(key)) {
      this.bgm = this.sound.add(key, { loop: true, volume: 0.4 });
      this.bgm.play();
    }
  }

  handleBiomeSwitch(biome) {
    // Fade in en vit overlay, byt biom, fade ut.
    const w = this.scale.width;
    const h = this.scale.height;
    const overlay = this.add.rectangle(w / 2, h / 2, w, h, 0xffffff, 0).setDepth(2000);
    this.tweens.add({
      targets: overlay,
      alpha: 1,
      duration: 250,
      onComplete: () => {
        this.bgImage.setTexture(`bg-${biome.id}`).setDisplaySize(w, h);
        this.ground.setTexture(`ground-${biome.id}`);
        this.cameras.main.setBackgroundColor(biome.bgColor);
        this.obstacleSpawner.setObstacleTypes(biome.obstacleTypes);
        this.pokemonSpawner.setPokemonIds(biome.pokemonIds);
        this.safeBgm(`bgm-${biome.id}`);
        this.tweens.add({
          targets: overlay,
          alpha: 0,
          duration: 350,
          onComplete: () => overlay.destroy(),
        });
      },
    });
  }

  update(time, delta) {
    // Gradvis speed-up: nå max efter ~90 sek.
    const elapsed = (this.time.now - this.startTime) / 1000;
    const ramp = Math.min(elapsed / 90, 1);
    this.scrollSpeed = this.baseSpeed + (this.maxSpeed - this.baseSpeed) * ramp;

    const inBonk = this.time.now < this.bonkUntilTime;
    const effectiveSpeed = inBonk ? this.scrollSpeed * 0.4 : this.scrollSpeed;
    this.biomeManager.tick(delta);
    this.ground.tilePositionX += (effectiveSpeed * delta) / 1000;

    // Delad puls för alla ringar (en sin-funktion istället för per-ring tweens).
    const phase = (Math.sin(this.time.now / 350) + 1) / 2;
    const pulseScale = 1 + phase * 0.15;
    const pulseAlpha = 0.4 + phase * 0.3;

    const airborne = !(this.bike.body.blocked.down || this.bike.body.touching.down);

    // Hinder
    this.timeSinceLastObstacleSpawn += delta;
    const obstacleEvent = this.obstacleSpawner.tick(delta, { bikeAirborne: airborne });
    if (obstacleEvent) {
      this.spawnObstacle(obstacleEvent.type);
      this.timeSinceLastObstacleSpawn = 0;
    }

    // Pokémon
    const pokemonEvent = this.pokemonSpawner.tick(delta, {
      timeSinceLastObstacleSpawn: this.timeSinceLastObstacleSpawn,
      bikeAirborne: airborne,
    });
    if (pokemonEvent) this.spawnPokemon(pokemonEvent);

    // Sätt aktuell hastighet på alla rörliga (inkl. ringar) + uppdatera ring-puls.
    this.obstacles.children.each((o) => {
      if (o && o.body) {
        o.setVelocityX(-effectiveSpeed);
        const ring = o.getData('ring');
        if (ring && ring.body) {
          ring.body.setVelocityX(-effectiveSpeed);
          ring.setScale(pulseScale);
          ring.setAlpha(pulseAlpha);
        }
      }
      return true;
    });
    this.pokemons.children.each((m) => {
      if (m && m.body && !m.getData('picked')) {
        m.setVelocityX(-effectiveSpeed);
        const ring = m.getData('ring');
        if (ring && ring.body) {
          ring.body.setVelocityX(-effectiveSpeed);
          ring.setScale(pulseScale);
          ring.setAlpha(pulseAlpha);
        }
      }
      return true;
    });

    // Cleanup (ta med ringen).
    this.obstacles.children.each((o) => {
      if (o && o.x < -100) {
        const ring = o.getData('ring');
        if (ring) ring.destroy();
        o.destroy();
      }
      return true;
    });
    this.pokemons.children.each((m) => {
      if (m && m.x < -100) {
        const ring = m.getData('ring');
        if (ring) ring.destroy();
        const trail = m.getData('trail');
        if (trail) trail.destroy();
        m.destroy();
      }
      return true;
    });
  }
}
